export const LANDING ="/";
export const HOME ="/home";
export const LOGIN = "/login";
export const SIGNUP = "/signup";
export const TEAM = "/team";
export const ABOUT = "/about";
export const CAUSE ="/cause";
export const BLOG = "/blog";
export const CONTACT = "/contact";